//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordOccurenceClient.Counter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Counter.ICounter")]
    public interface ICounter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICounter/GetData", ReplyAction="http://tempuri.org/ICounter/GetDataResponse")]
        int GetData(string substring, string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICounter/GetData", ReplyAction="http://tempuri.org/ICounter/GetDataResponse")]
        System.Threading.Tasks.Task<int> GetDataAsync(string substring, string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICounterChannel : WordOccurenceClient.Counter.ICounter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CounterClient : System.ServiceModel.ClientBase<WordOccurenceClient.Counter.ICounter>, WordOccurenceClient.Counter.ICounter {
        
        public CounterClient() {
        }
        
        public CounterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CounterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetData(string substring, string word) {
            return base.Channel.GetData(substring, word);
        }
        
        public System.Threading.Tasks.Task<int> GetDataAsync(string substring, string word) {
            return base.Channel.GetDataAsync(substring, word);
        }
    }
}
