//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalendarViewer.Viewer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Viewer.ICalendarViewer")]
    public interface ICalendarViewer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarViewer/GetData", ReplyAction="http://tempuri.org/ICalendarViewer/GetDataResponse")]
        string GetData(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalendarViewer/GetData", ReplyAction="http://tempuri.org/ICalendarViewer/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalendarViewerChannel : CalendarViewer.Viewer.ICalendarViewer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalendarViewerClient : System.ServiceModel.ClientBase<CalendarViewer.Viewer.ICalendarViewer>, CalendarViewer.Viewer.ICalendarViewer {
        
        public CalendarViewerClient() {
        }
        
        public CalendarViewerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalendarViewerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarViewerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalendarViewerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(System.DateTime date) {
            return base.Channel.GetData(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(System.DateTime date) {
            return base.Channel.GetDataAsync(date);
        }
    }
}
