USE [master]
GO
/****** Object:  Database [MusicStoreDB]    Script Date: 8/7/2013 2:24:35 PM ******/
CREATE DATABASE [MusicStoreDB]
 CONTAINMENT = NONE 
GO
ALTER DATABASE [MusicStoreDB] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MusicStoreDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MusicStoreDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MusicStoreDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MusicStoreDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MusicStoreDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MusicStoreDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MusicStoreDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MusicStoreDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [MusicStoreDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MusicStoreDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MusicStoreDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MusicStoreDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MusicStoreDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MusicStoreDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MusicStoreDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MusicStoreDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MusicStoreDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MusicStoreDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MusicStoreDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MusicStoreDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MusicStoreDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MusicStoreDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MusicStoreDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MusicStoreDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MusicStoreDB] SET RECOVERY FULL 
GO
ALTER DATABASE [MusicStoreDB] SET  MULTI_USER 
GO
ALTER DATABASE [MusicStoreDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MusicStoreDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MusicStoreDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MusicStoreDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MusicStoreDB', N'ON'
GO
USE [MusicStoreDB]
GO
/****** Object:  Table [dbo].[Albums]    Script Date: 8/7/2013 2:24:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Albums](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Date] [date] NULL,
	[Producer] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Albums] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Artists]    Script Date: 8/7/2013 2:24:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Artists](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
	[Country] [nvarchar](50) NOT NULL,
	[DateOfBirth] [date] NULL,
	[AlbumId] [int] NOT NULL,
 CONSTRAINT [PK_Artists] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Songs]    Script Date: 8/7/2013 2:24:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Songs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TItle] [nvarchar](50) NOT NULL,
	[Date] [date] NULL,
	[Ganre] [nvarchar](50) NOT NULL,
	[ArtistId] [int] NOT NULL,
	[AlbumId] [int] NOT NULL,
 CONSTRAINT [PK_Songs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Artists]  WITH CHECK ADD  CONSTRAINT [FK_Artists_Albums] FOREIGN KEY([AlbumId])
REFERENCES [dbo].[Albums] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Artists] CHECK CONSTRAINT [FK_Artists_Albums]
GO
ALTER TABLE [dbo].[Songs]  WITH CHECK ADD  CONSTRAINT [FK_Songs_Albums] FOREIGN KEY([AlbumId])
REFERENCES [dbo].[Albums] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Songs] CHECK CONSTRAINT [FK_Songs_Albums]
GO
ALTER TABLE [dbo].[Songs]  WITH CHECK ADD  CONSTRAINT [FK_Songs_Artists] FOREIGN KEY([ArtistId])
REFERENCES [dbo].[Artists] ([id])
GO
ALTER TABLE [dbo].[Songs] CHECK CONSTRAINT [FK_Songs_Artists]
GO
USE [master]
GO
ALTER DATABASE [MusicStoreDB] SET  READ_WRITE 
GO
